### ISSUE TITLE
[Bug] Overtime bonus calculation

### ISSUE THREAD

**Issue by JohnMetroid** [ZehsTeam/Lethal-Company-SellMyScrap#11]
Hey there,

Encountered a bug with the displayed value of the Overtime Bonus while playing tonight and figured I'd report it.  No issues thrown in the log, or anything wonky going on as far as I could tell.

![image](https://github.com/user-attachments/assets/d9a050ec-84ad-46a0-adef-8d3cdbbc6410)

Cheers

**Comment by ZehsTeam** [comment]
@ajsglist The Company requires you to pay them for not working enough hours.

JK it's just the overtime bonus calculation formula. You won't lose 5 credits.

**Comment by ZehsTeam** [comment]
This has been fixed in the latest update [SellMyScrap v1.6.0](https://thunderstore.io/c/lethal-company/p/Zehs/SellMyScrap/) - [c75eb15](https://github.com/ZehsTeam/Lethal-Company-SellMyScrap/commit/c75eb15a712a9d9a5cbbd1f4002051d714f22e3b)

**Comment by JohnMetroid** [comment]
Hey, just a heads up: the overtime bonus still isn't calculating correctly

![image](https://github.com/user-attachments/assets/8291368e-e45b-42a5-bfbb-a89b3000fd8d)

**Comment by ZehsTeam** [comment]
@ajsglist This will be fixed in the next update.

**Comment by ZehsTeam** [comment]
@ajsglist This has been fixed in the latest update [SellMyScrap v1.7.0](https://thunderstore.io/c/lethal-company/p/Zehs/SellMyScrap/) - [cef3cd5](https://github.com/ZehsTeam/Lethal-Company-SellMyScrap/commit/cef3cd5b5bd213fc2f9b6bbed409bb750746a032)
